### ISSUE TITLE
Allow to extend BaseAI

### ISSUE THREAD

**Issue by cliren** [dosco/llm-client#11]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

We have a special AI client that customizes existing AI like Anthropic, Bedrock and OpenAI. In order to use llm-client with them, it helps to build on top of llm-client and requesting to make it possible. 

1. BaseAI - https://github.com/dosco/llm-client/blob/main/src/ai/base.ts#L43 OR
2. a better alternative.

**Comment by dosco** [comment]
I'd suggest just extending BaseAI to add your own ai client. Maybe I'm not understanding this well enough. Feel free to msg on our discord.
