### ISSUE TITLE
Cohere AI provider error

### ISSUE THREAD

**Issue by juliankrispel** [dosco/llm-client#12]
## I'm submitting a bug report

- **Summary**
The following code causes the exception: `Cannot read properties of undefined (reading 'map')`, this happens when calling `a.forward`

```
const ai = new Anthropic({
  apiKey,
});
const cot = new ChainOfThought(
  ai,
  `question:string -> answer:string`
);
const res = await a.forward({ question });
```

**Comment by dosco** [comment]
I think you meant Anthropic not Cohere in the title. I've made the fixes in the latest release 8.0.5 and tested both Anthropic and Cohere.
