### ISSUE TITLE
Adding output parsers to spaces

### ISSUE THREAD

**Issue by itsyogesh** [dosco/llm-client#3]
There is a lot of work that's happening around llm outputs. Some interesting things we can look at:

https://hwchase17.github.io/langchainjs/docs/modules/prompts/output_parsers/

https://github.com/shreyar/guardrails

https://eyurtsev.github.io/kor/index.html

We can look at specific implementations that are described here or we can build one from scratch.

**Comment by dosco** [comment]
Thanks this looks cool i'll dig in deeper. There are two built in output parsers in `GenerateText` both are used based on `Prompt` metadata for example. the param `keyValueResponse: true` enables splitting the response using a colon seperator. 

1. Key Value Output: https://github.com/dosco/minds/blob/50e864f91806c2d723fe6edd46bc3a6a2ecd17d8/src/prompts/extract.ts#LL75C7-L75C23

2. Tools / Actions but this one is used internally:
https://github.com/dosco/minds/blob/50e864f91806c2d723fe6edd46bc3a6a2ecd17d8/src/prompts/answers.ts#L46
 
I tend to add features based on uses-cases so will try and figure out some to extending our current output parsing the zod librasry that langchain uses can be used by us as well.

**Comment by dosco** [comment]
just finished a big refactor to make the api simpler to use and extend. also added support for zod. we now have output parser support for plaintext, simple key-value or a zod schema built in.

The prompts are now super-simple and mostly extend from `AIPrompt` which does all the heavy lifting. For example see the 
https://github.com/dosco/minds/blob/main/src/prompts/zprompt.ts

```
const prompt = new ZPrompt(zodSchema, actions);
```

```
const CustomerResponse = z.object({
  data: z
    .array(
      z.object({
        name: z.string().describe('product name'),
        units: z.number().describe('units in stock'),
        desc: z.string().max(15).describe('product description'),
      })
    )
    .describe('inventory information'),
  response: z.string().max(50).describe('customer response'),
});

const prompt = new ZPrompt(CustomerResponse, actions);
```

**Comment by Madd0g** [comment]
Are ZPrompt or zod (or grammars) supported currently? I couldn't find anything

**Comment by dosco** [comment]
The whole framework has changed significantly and is now based on the prompt as. a program idea from the Stanford DSP  paper. while zod is not supported anymore it's not required you can have typed inputs and outputs on the prompt (prompt signature)

**Comment by dosco** [comment]
And you can use `asserts` to integrate with zod if you still need to.
