### ISSUE TITLE
Ask-Question.js

### ISSUE THREAD

**Issue by jox51** [dosco/llm-client#9]
Dosco, in the examples folder you have an ask-questions.js file mentioned in the readme but the actual file example is not linked. This the file that shows how to use Google Search with your library. Any chance you can add it?

**Comment by dosco** [comment]
That example used an old version of function calling that we has used before we had real function calling. The example was removed. If you want to call google search just create a wrapper function of your own using https://serpapi.com/ and use it with the function calling feature of the library. Many of the examples including `product-search.js` are good examples of how to do this

**Comment by jox51** [comment]
Thank you, been using your library on a current project and like it alot. Looking forward to seeing how you continue developing it.

**Comment by jox51** [comment]
Thank you, been using your library on a current project and like it alot. Looking forward to seeing how you continue developing it.
